config/routes.rb
MobilereportMturk::Application.routes.draw do
  resources :recordings
  resources :scripts

end

app/models/recording.rb
class Recording < ActiveRecord::Base
  validates_presence_of :gender, :locale
  validates_inclusion_of :gender, :in => %w(Male Female)
  validates_attachment_presence :soundfile
  validates_attachment_content_type :soundfile, :content_type => ['audio/x-wav', 'audio/wav']

  has_attached_file :soundfile
  belongs_to :script

  GENDERS = %w[Male Female]
end

# == Schema Information
#
# Table name: recordings
#
#  id                     :integer         not null, primary key
#  gender                 :string(255)
#  locale                 :string(255)
#  soundfile_file_name    :string(255)
#  soundfile_content_type :string(255)
#  soundfile_updated_at   :datetime
#  created_at             :datetime
#  updated_at             :datetime
#

app/models/script.rb
class Script < ActiveRecord::Base
  validates_presence_of :body

  has_many :recordings

  def self.random
    if (c = count) != 0
      find(:first, :offset =>rand(c))
    else
      Script.new(:body => "There are no scripts available for recording.")
    end
  end
end

# == Schema Information
#
# Table name: scripts
#
#  id         :integer         not null, primary key
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  # GET /recordings
  # GET /recordings.xml
  def index
    @recordings = Recording.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @recordings }
    end
  end

  # GET /recordings/1
  # GET /recordings/1.xml
  def show
    @recording = Recording.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @recording }
    end
  end

  # GET /recordings/new
  # GET /recordings/new.xml
  def new
    @recording = Recording.new
    @script = Script.random

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recording }
    end
  end

  # GET /recordings/1/edit
  def edit
    @recording = Recording.find(params[:id])
    @script = @recording.script
  end

  # POST /recordings
  # POST /recordings.xml
  def create
    @recording = Recording.new(params[:recording])

    respond_to do |format|
      if @recording.save
        format.html { redirect_to(@recording, :notice => 'Recording was successfully created.') }
        format.xml  { render :xml => @recording, :status => :created, :location => @recording }
      else
        @script = Script.find(params[:recording][:script_id])
        format.html { render :action => "new" }
        format.xml  { render :xml => @recording.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recordings/1
  # PUT /recordings/1.xml
  def update
    @recording = Recording.find(params[:id])

    respond_to do |format|
      if @recording.update_attributes(params[:recording])
        format.html { redirect_to(@recording, :notice => 'Recording was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recording.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recordings/1
  # DELETE /recordings/1.xml
  def destroy
    @recording = Recording.find(params[:id])
    @recording.destroy

    respond_to do |format|
      format.html { redirect_to(recordings_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  # GET /scripts
  # GET /scripts.xml
  def index
    @scripts = Script.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scripts }
    end
  end

  # GET /scripts/1
  # GET /scripts/1.xml
  def show
    @script = Script.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @script }
    end
  end

  # GET /scripts/new
  # GET /scripts/new.xml
  def new
    @script = Script.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @script }
    end
  end

  # GET /scripts/1/edit
  def edit
    @script = Script.find(params[:id])
  end

  # POST /scripts
  # POST /scripts.xml
  def create
    @script = Script.new(params[:script])

    respond_to do |format|
      if @script.save
        format.html { redirect_to(@script, :notice => 'Script was successfully created.') }
        format.xml  { render :xml => @script, :status => :created, :location => @script }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @script.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scripts/1
  # PUT /scripts/1.xml
  def update
    @script = Script.find(params[:id])

    respond_to do |format|
      if @script.update_attributes(params[:script])
        format.html { redirect_to(@script, :notice => 'Script was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @script.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scripts/1
  # DELETE /scripts/1.xml
  def destroy
    @script = Script.find(params[:id])
    @script.destroy

    respond_to do |format|
      format.html { redirect_to(scripts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobilereportMturk</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recordings/_form.html.erb
<%= form_for @recording, :as => :recording, :url => recordings_path, :html => { :multipart => true } do |f| %>
  <% if @recording.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recording.errors.count, "error") %> prohibited this recording from being saved:</h2>

      <ul>
      <% @recording.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gender %><br />
    <%= select :recording, :gender, Recording::GENDERS, :include_blank => 'Select a Gender' %>
  </div>
  <div class="field">
    <%= f.label :locale %><br />
    <%= f.text_field :locale %>
  </div>
  <div class="field">
    <%= f.label :soundfile, "Sound File" %><br />
    <%= f.file_field :soundfile %>
  </div>
  <div class="field-hidden">
    <%= f.hidden_field :script_id, :value => @script.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recordings/edit.html.erb
<h1>Editing recording</h1>

<%= render 'form' %>

<%= link_to 'Show', @recording %> |
<%= link_to 'Back', recordings_path %>

app/views/recordings/index.html.erb
<h1>Listing recordings</h1>

<table>
  <tr>
    <th>Gender</th>
    <th>Locale</th>
    <th>Soundfile file name</th>
    <th>Soundfile content type</th>
    <th>Soundfile updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recordings.each do |recording| %>
  <tr>
    <td><%= recording.gender %></td>
    <td><%= recording.locale %></td>
    <td><%= recording.soundfile_file_name %></td>
    <td><%= recording.soundfile_content_type %></td>
    <td><%= recording.soundfile_updated_at %></td>
    <td><%= link_to 'Show', recording %></td>
    <td><%= link_to 'Edit', edit_recording_path(recording) %></td>
    <td><%= link_to 'Destroy', recording, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recording', new_recording_path %>

app/views/recordings/new.html.erb
<h1>New recording</h1>

<h2>Script for recording:</h2>

<%= @script.body %>

<%= render 'form' %>

<%= link_to 'Back', recordings_path %>

app/views/recordings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gender:</b>
  <%= @recording.gender %>
</p>

<p>
  <b>Locale:</b>
  <%= @recording.locale %>
</p>

<p>
  <b>Soundfile file name:</b>
  <%= @recording.soundfile_file_name %>
</p>

<p>
  <b>Soundfile content type:</b>
  <%= @recording.soundfile_content_type %>
</p>

<p>
  <b>Soundfile updated at:</b>
  <%= @recording.soundfile_updated_at %>
</p>


<%= link_to 'Edit', edit_recording_path(@recording) %> |
<%= link_to 'Back', recordings_path %>

app/views/scripts/_form.html.erb
<%= form_for(@script) do |f| %>
  <% if @script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@script.errors.count, "error") %> prohibited this script from being saved:</h2>

      <ul>
      <% @script.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scripts/edit.html.erb
<h1>Editing script</h1>

<%= render 'form' %>

<%= link_to 'Show', @script %> |
<%= link_to 'Back', scripts_path %>

app/views/scripts/index.html.erb
<h1>Listing scripts</h1>

<table>
  <tr>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scripts.each do |script| %>
  <tr>
    <td><%= script.body %></td>
    <td><%= link_to 'Show', script %></td>
    <td><%= link_to 'Edit', edit_script_path(script) %></td>
    <td><%= link_to 'Destroy', script, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Script', new_script_path %>

app/views/scripts/new.html.erb
<h1>New script</h1>

<%= render 'form' %>

<%= link_to 'Back', scripts_path %>

app/views/scripts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @script.body %>
</p>


<%= link_to 'Edit', edit_script_path(@script) %> |
<%= link_to 'Back', scripts_path %>